// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgl1Atm1yNpcGn0y3MgKNjTfN9NDrpzUo',
    appId: '1:347396343329:web:338174d6338e38cdc20560',
    messagingSenderId: '347396343329',
    projectId: 'busmap-11e7c',
    authDomain: 'busmap-11e7c.firebaseapp.com',
    storageBucket: 'busmap-11e7c.firebasestorage.app',
    measurementId: 'G-VL9FCB54QX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZLsEDmZFF5IY5d0UAWXnS7CHV3zu1tto',
    appId: '1:347396343329:android:c701e78ece1b9851c20560',
    messagingSenderId: '347396343329',
    projectId: 'busmap-11e7c',
    storageBucket: 'busmap-11e7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0o1M4A3AJHX3dC-ZHViqinOUq1xRuj5o',
    appId: '1:347396343329:ios:1b0d736fca5cdf2dc20560',
    messagingSenderId: '347396343329',
    projectId: 'busmap-11e7c',
    storageBucket: 'busmap-11e7c.firebasestorage.app',
    iosBundleId: 'com.example.mapbus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0o1M4A3AJHX3dC-ZHViqinOUq1xRuj5o',
    appId: '1:347396343329:ios:1b0d736fca5cdf2dc20560',
    messagingSenderId: '347396343329',
    projectId: 'busmap-11e7c',
    storageBucket: 'busmap-11e7c.firebasestorage.app',
    iosBundleId: 'com.example.mapbus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgl1Atm1yNpcGn0y3MgKNjTfN9NDrpzUo',
    appId: '1:347396343329:web:9750da0287793f99c20560',
    messagingSenderId: '347396343329',
    projectId: 'busmap-11e7c',
    authDomain: 'busmap-11e7c.firebaseapp.com',
    storageBucket: 'busmap-11e7c.firebasestorage.app',
    measurementId: 'G-FLVV11X830',
  );
}
