server.port=8080
# ??a ch? k?t n?i t?i MySQL trong XAMPP
spring.datasource.url=jdbc:mysql://localhost:3306/bus_map?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC



spring.datasource.username=root


spring.datasource.password=


spring.jpa.hibernate.ddl-auto=update


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=trace
google.api.key=AIzaSyB2ytHsCcG2F6TKjPZEqgYs1aP-pBnflFA
spring.security.user.name=dat123456
spring.security.user.password=dat123456
YOUR_GOOGLE_MAPS_API_KEY=AIzaSyB2ytHsCcG2F6TKjPZEqgYs1aP-pBnflFA
google.maps.api.key=AIzaSyB2ytHsCcG2F6TKjPZEqgYs1aP-pBnflFA